### ISSUE TITLE
Handle prefix errors not logging

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#613]
**ISSUE**

Handle registration jobs show up in resque as failed, but I don't get any error logging If I have a bad prefix in my configuration like:
```yaml
handle_prefix:      "10427.TESTY"
```

**Comment by jcoyne** [comment]
```ruby
NoMethodError: undefined method `scan' for nil:NilClass
/opt/mira/shared/bundle/ruby/2.1.0/bundler/gems/handle-75986eeedaa9/lib/handle/command/connection.rb:117:in `resolve_handle'
/opt/mira/shared/bundle/ruby/2.1.0/bundler/gems/handle-75986eeedaa9/lib/handle/command/persistence.rb:31:in `save'
```

**Comment by jcoyne** [comment]
Caused by https://github.com/mbklein/handle/issues/3

**Comment by jcoyne** [comment]
Closed by eb92adb
