### ISSUE TITLE
Item show view failing

### ISSUE THREAD

**Issue by mark-dce** [curationexperts/mira#653]
When I click on an item in any search results list, the catalog sow view gives me an error:

```text
Showing /Users/mark/Documents/workspace/_no_backup/RubymineProjects/mira/app/views/catalog/_show_datastream_download_link.html.erb where line #2 raised:

undefined local variable or method `title' for #<#<Class:0x00000102c40420>:0x00000108214ce8>
...
```

**Comment by mark-dce** [comment]
git bisect points to this commit:
5ff0e1a553be68f9b2102aae1817082bf7d6d9a1 display the document's transfer binary filename for PDFs. fixes #640  

Upon further investigation, the error occurs on all objects except TuftsPDF.  The download link partial was refactored to accommodate saving the original filename associated with the Transfer.binary datastream.  Other object views which call the partial no longer pass the expected locals to the partial.

eg. \_show_text_pdf passes 'title' while  \_show_tufts_video passes 'download_section_title' instead.  The download link partial expects a 'filename' which is only passed from the pdf view but not the views for other objects.
